Repository gosimple/slug, pull requests merged in 2024-02, with the labels that each got.

#83 Fix some order dependent tests
  slug_test.go
Labels: tests

#86 Remove rebase Github action
  .github/workflows/rebase.yml
Labels: maintenance

#79 Adds portuguese language & @ symbols
  languages_substitution.go
  slug.go
  slug_test.go
Labels: enhancement

#81 Add AppendTimestamp option to make slug unique
  slug.go
  slug_test.go
Labels: enhancement
